---
title: "gender_ml"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load libraries
library(stm)
library(tidyverse)
library(caret)
library(quanteda)
```
 
```{r}
#import data
guardian <- readRDS("guardian.RDS")
df <- guardian %>% select(outlet, text, gender)
```


```{r}
#split data into training and test set
set.seed(123)

index <- createDataPartition(df$gender, p =0.7, list = FALSE)

train <- df[index, ]
test <- df[-index, ]

#create variable to denote if observation is train or test
train$train_test <- c("train")
test$train_test <- c("test")

#merge train and test data
merged <- rbind(train, test)

#remove test and train
remove(train, test)

table(merged$gender, merged$train_test)
```

#Preprocessing

```{r}

#function to generate dfm
makeDFM <- function(df) {
  corpus <- corpus(df, text_field = "text")
  doctm <- dfm(corpus, remove=stopwords("english"), verbose=TRUE,
                ngrams = 1L,
                stem = F,
     remove_punct=TRUE, remove_numbers=TRUE, remove_symbols = TRUE)
  
  doctm <- dfm_trim(doctm, min_termfreq = 10, min_docfreq = 20)
  
  return(doctm)
}

```

```{r}
#create dfm
merged_dfm <- makeDFM(merged)

#create tf-idf weighted version of dfm
merged_dfm_weighted <- dfm_tfidf(merged_dfm)

#convert dfm's to dataframes
merged_dfm <- convert(merged_dfm, to = "data.frame")
merged_dfm_weighted <- convert(merged_dfm_weighted, to = "data.frame")

```

```{r}
#split back into train and test sets
dfmTrain <- merged_dfm[which(merged$train_test == "train"), ]
weightedDFMtrain <- merged_dfm_weighted[which(merged$train_test == "train"), ]

dfmTest <- merged_dfm[which(merged$train_test == "test"), ]
weightedDFMtest <- merged_dfm_weighted[which(merged$train_test == "test"), ]

#append article labels as last column
dfmTrain$author_gender <- merged$gender[which(merged$train_test == "train")]
dfmTest$author_gender <- merged$gender[which(merged$train_test == "test")]
weightedDFMtrain$author_gender <- merged$gender[which(merged$train_test == "train")]
weightedDFMtest$author_gender <- merged$gender[which(merged$train_test == "test")]
```


```{r}

```

